---
# This is temporarily disabled because of:
# http://tracker.ceph.com/issues/13572
#apt_repos:
#  # blkin libraries, only trusty has new enough lttng for these
#  - "deb [arch=amd64] http://{{ mirror_host }}/blkin/ trusty main"

packages:
  - libboost-thread1.58.0
  - mpich
  - qemu-system-x86
#  - blkin
  - lttng-tools
  ###
  # for setting BIOS settings
  ###
  - libcrypto++9v5
  ###
  # for building xfstests #18067
  - libtool-bin

packages_to_upgrade:
  # http://tracker.ceph.com/issues/13522#note-51
  - libgoogle-perftools4

non_aarch64_packages:
  - libgoogle-perftools4
  - iozone3
  - libssl1.0.0
